### ISSUE TITLE
Code rendering issue

### ISSUE THREAD

**Issue by harikt** [thecodingmachine/database.tdbm#113]
Hi, 

Was going through the documentation https://github.com/thecodingmachine/database.tdbm/blob/4.2/doc/quickstart.md#discarding-parameters-automatically-with-magic-parameters and noticed some code ( Just above paragraph of the link provided ) like

php // NEVER DO THIS! $list = $this->find("name LIKE '".$firstLetter.'%"' ); 

The code is actually written inside div. So I am not sure if that can be fixed or it is using a different approach to show on website. 

Just thought of bringing it here for I wasn't able to fix it .

**Comment by moufmouf** [comment]
Hi Hari,

Thanks a lot for the feedback. Actually, the div with not properly closed which caused the code to not be displayed correctly.

I fixed this [here](https://github.com/thecodingmachine/database.tdbm/commit/09a012cd11441a4d2d0bf956bdb4aef5302c763f)

> So I am not sure if that can be fixed or it is using a different approach to show on website. 

Indeed, you are correct. The documentation is generated and available here in a slightly nicer format than on Github:

http://mouf-php.com/packages/mouf/database.tdbm/version/4.2-dev/doc/quickstart.md

Also, if you are interested in a quick presentation, I've put up some slides here : http://moufmouf.github.io/tdbm4-slides/#/

By the way, I'd be interested in any feedback regarding TDBM. How did you come to have a look at it? Does its approach seem interesting to you?

**Comment by harikt** [comment]
> Also, if you are interested in a quick presentation, I've put up some slides here :  http://moufmouf.github.io/tdbm4-slides/#/

Nice slides. Thank you for the link.

> By the way, I'd be interested in any feedback regarding TDBM. 

I was just exploring the code. And consider me having some interest to learn about ORM's implementation.

> How did you come to have a look at it? 

I already know / have heard about mouf, and you. Recently just came across your profile via the container-intero repo. And noticed the repo, just was reading the README. ie it :-) .

> Does its approach seem interesting to you?

Yes of-course I like some of the concepts, but wasn't aware it was ActiveRecord. I have not looked more into the code.

Hope that helps.

Thank you.

**Comment by harikt** [comment]
Forget to mention a few things.
1. Probably want to get rid of mouf to generate the DAO. Use some cli tool. ( Noticed you mentioned the same)
2. Examples starts with DAO. It probably is good to create tables, and create DAO / Bean first so users understand how the classes come.
