### ISSUE TITLE
same method name declared twice if one table points to another on with one2Many AND manyToMany table

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/database.tdbm#127]
Example : A points to B through a.b_id foreign key AND also has a pivot table : AB that joins A and B in a many2many relationship.

TDBM will generate the same method twice in B Class : getA(), that returns a list of A, first one through a.b_id FK, and second one through AB pivot table

**Comment by moufmouf** [comment]
This is a duplicate from #125 (and is still an open bug)
