### ISSUE TITLE
findOne parameters in generated Daos

### ISSUE THREAD

**Issue by cbalda** [thecodingmachine/database.tdbm#138]
Has you can see in generated methods about findOne()'s call case (in case on indexed columns), you give 5 parameters to this one ($filter, [], $orderBy, $additionalTablesFetch, $mode).
But, the findOne() function must have, at most, 2 parameters ($filter = null, array $parameters = []).

In this case, $orderBy is useless.

So, we can modify findOne to have at most 4 parameters ($filter = null, array $parameters = [], array $additonalTablesFetch = [], $mode = null).

**Comment by moufmouf** [comment]
Closed in 4.3
