### ISSUE TITLE
count() impossible on primary key with multiple columns

### ISSUE THREAD

**Issue by Zheness** [thecodingmachine/database.tdbm#151]
Hi,

The query formated after doing a count() is missing commas (`,`) if the table contains a primary key on multiple columns. 

Ex:

```
An exception occurred while executing 'SELECT \n  COUNT(     DISTINCT    `event_participation`.`nid`   `event_participation`.`idcompany`)\nFROM   `event_participation` [...]
```

Thanks !

**Comment by moufmouf** [comment]
Fixed by https://github.com/thecodingmachine/magic-query/pull/40
