### ISSUE TITLE
Wrong return type for "findOneBy" methods generated for unique column

### ISSUE THREAD

**Issue by jeremiepose** [thecodingmachine/database.tdbm#152]
In base dao, when there is a unique index on a column, TDBM generates a "findOneByColumn" method. This method has a wrong return type. For example : 

```
    /**
     * Get a Member filtered by email.
     *
     * @param string $email
     * @param array $additionalTablesFetch A list of additional tables to fetch (for performance improvement)
     * @return Member
     */
    public function findOneByEmail($email, array $additionalTablesFetch = array()) : Member
    {
        $filter = [
            'email' => $email,
        ];
        return $this->findOne($filter, [], $additionalTablesFetch);
    }
```
The return type should be Member|null

**Comment by moufmouf** [comment]
Isn't this already fixed?
Did you try a composer update first?

Le lun. 30 oct. 2017 à 18:51, Jérémie Posé <notifications@github.com> a
écrit :

**Comment by jeremiepose** [comment]
Indeed, this is already fixed. My apologies !  :+1:
