### ISSUE TITLE
About documentation: Advanced tutorial

### ISSUE THREAD

**Issue by npeguin** [thecodingmachine/database.tdbm#3]
In the section "More about the filter bag" there are bad syntaxes or old syntaxes: 
$france = $this-&gt;getCountryListByFilter("countries.country_name='France'"); for "->"
new TDBM_EqualFilter replaced by new EqualFilter
new TDBM_OrderByColumn replaced by new OrderByColumn
It could be interesting to add an example about auto JOINING.

**Comment by moufmouf** [comment]
Fixed.
