### ISSUE TITLE
TDBM

### ISSUE THREAD

**Issue by cbalda** [thecodingmachine/database.tdbm#34]
Add mapping between tables and beans' names which allows users not to specify className in request like tdbmService->getObjectsFromSql()

**Comment by moufmouf** [comment]
TODO:

Add a `setTableToBeanMap(array $map)` function in TDBMService.
This function contains as a key the table name and as a value the fully qualified class name of the bean.

Each time we need to instanciate a bean, we can (optionnally) look in this table.
This table can be initialized in MoufComponents (when we regenerate the DAOs)
