### ISSUE TITLE
Rename egt/setters by object for foreignKeys

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/database.tdbm#47]
Ex: a `User` Bean that has embedds a `City` one (user.city_id). This will generate the following setters/getters :

``` php
 * get/setCityId(int $cityId);
 * get/setCity(CityBean $city);
 * get/setCityByCityId(CityBean $city);
```

The last two setters are named according to the referenced table (city), which is nice, but confusing when there is more than 1 FK pointing to the same table. Ex : user.city_id and user.birth_city_id, and also generates very long method names.

Would it be possible, ini next version to make something like that :

``` php
 * get/setCityId(int $cityId);
 * get/setBirthCityId(int $birtjCityId);

 * get/setCity(CityBean $city);
 * get/setBirthCity(CityBean $city);
```

... by looking for id_... or ..._id patterns in foreign keys columns. If those patterns are not found, then the accessors could just be named by the column (camelcase) name.

**Comment by moufmouf** [comment]
Already done (in next 4.0)! :)
