### ISSUE TITLE
isset tdbmarray object

### ISSUE THREAD

**Issue by FloSeas** [thecodingmachine/database.tdbm#6]
in  src / Mouf / Database / TDBM / TDBMObject

When whe have an empty arrayObject the function isset does not detect it.

I don't really know your code but

when must use ->count of arrayObject

i don't know if it's a php bug due to 

https://bugs.php.net/bug.php?id=61347 and https://bugs.php.net/bug.php?id=62059

Should be, the behavior of the issetSet is strange on arrayObject, but it's pretty inappropriate not beeing able to do isset on an empty object

**Comment by moufmouf** [comment]
Could you maybe give me a small code sample that helps me reproduce the problem?

**Comment by moufmouf** [comment]
TDBMObjectArray is gone in TDBM 4.0.
