### ISSUE TITLE
Recursion detected

### ISSUE THREAD

**Issue by FloSeas** [thecodingmachine/database.tdbm#7]
Hello,

after few attempts if found there was recusion on objects.

The Dao of the project i work on is not from me but supposing it is a nice programmed Dao i may use bad my objects?

In fact in my controller I do the following:

$this->something = $this->daoFactory->getSomething Dao()->getList(); 

and in my view when I print_r($this->something) php detect recursion.

Do I do Something wrong?

**Comment by moufmouf** [comment]
Hi,

No, there is nothing wrong and it is not a bug in TDBM.
What happens is that beans are referencing the TDBM_Service and the TDBM_Service is referencing all the beans in a big array.
When you try to "print_r" a bean, print_r enters in an infinite loop. This is a limitation of the print_r function in PHP that does not know how to handle recursion.
You might want to try "var_dump" instead. It is more clever when it comes to printing complex objects (especially if you use the xdebug extension that overloads the behaviour of var_dump)

**Comment by FloSeas** [comment]
ok ty for clearing my mind in this case
