### ISSUE TITLE
Seems lazy loading is not working...

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/database.tdbm#9]
Example : 

```
$users = $this->getListByFilter(...);
var_dump($users);
```

--> gives an empty TDBM Array even if SQL returns rows

Seems to be caused by broken lazy loading because when trying to access $users[0], IDE inspector returns a `UserBean` and `var_dump` is the expected...

**Comment by moufmouf** [comment]
Ha.... this is not a bug... it's a feature :)

The TDBMObjectArray is filled when we first iterate the array (using foreach) or when we first access the array using `$users[0]`.

Before, it contains nothing except a pointer to the `PDOStatement` that is used to fetch the values.
