### ISSUE TITLE
Error when calling a method using TDBMService in a bean

### ISSUE THREAD

**Issue by jfbujoli** [thecodingmachine/database.tdbm#99]
Getting the following error when using a method using TDBMService :
Call to a member function findObjects() on null

**Comment by moufmouf** [comment]
The problem:

TDBM handles correctly many to many relationships in "disconnected" mode, but not many-to-one relationships.

Code generated in the base bean:

``` php
    public function getUsers()
    {
        return $this->tdbmService->findObjects('users', 'users.country_id = :tdbmparam0', [ 'tdbmparam0' => $this->get('id', 'country') ]);
    }

```

We should instead call an internal function that either performs this manages the array for us.

Also, this means overriding setters to add values to the internal "many-to-one" collection.

This will take some time to solve.

**Comment by moufmouf** [comment]
Just added a test case to confirm the problem: https://github.com/moufmouf/database.tdbm/blob/bugfix/99-disconnected-many-to-one/tests/Mouf/Database/TDBM/TDBMDaoGeneratorTest.php#L1028-L1041
